using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.Data.SqlClient;
using Common.DotNetUI;

namespace FinanceOS
{
    public partial class FrmFinance_Settle_Month : Form
    {
        private string strLogID;
        private string strName;
        private string strRealName;

        public FrmFinance_Settle_Month()
        {
            InitializeComponent();
        }

        private void FrmFinance_Settle_Month_Load(object sender, EventArgs e)
        {
            if (AppDomain.CurrentDomain.GetData("LOGINID") != null && AppDomain.CurrentDomain.GetData("LOGINID") != DBNull.Value)
            {
                strLogID = AppDomain.CurrentDomain.GetData("LOGINID").ToString();
                strName = AppDomain.CurrentDomain.GetData("LOGINNAME").ToString();
                strRealName = AppDomain.CurrentDomain.GetData("USERNAME").ToString();

                BindData();
            }
            else
            {
                MessageBox.Show("收费员姓名获取失败!请重新打开该窗体!");
                this.Close();
            }
        }

        private void Btn_Search_Click(object sender, EventArgs e)
        {
            ShowData();
        }
        private void BindData()
        {
            DataTable dt = new DataTable();
            string sqlstr = @"SELECT DISTINCT ChargeMonth,ChargeMonth AS ChargeMonthVALUE FROM View_ChargeOver ORDER BY ChargeMonth DESC";
            dt = new SqlServerHelper().GetDateTableBySql(sqlstr, new SqlParameter[] { new SqlParameter("@LoginID", strLogID) });
            ControlBindHelper.BindComboBoxData(this.CB_Month, dt, "ChargeMonthVALUE", "ChargeMonth");

            sqlstr = @"SELECT DISTINCT CHARGEWORKERID,CHARGEWORKERNAME FROM View_ChargeOver ORDER BY CHARGEWORKERID DESC";
            dt = new SqlServerHelper().GetDateTableBySql(sqlstr, new SqlParameter[] { new SqlParameter("@LoginID", strLogID) });
            ControlBindHelper.BindComboBoxData(this.CB_LogID, dt, "CHARGEWORKERNAME", "CHARGEWORKERID");

            ShowData();
        }

        private void ShowData()
        {
            string sqlstr = string.Format(@"DECLARE @LoginID NVARCHAR(50)='{0}'
DECLARE @ChargeMonth NVARCHAR(50)='{1}'
 DECLARE @FEE decimal(18, 2)
 DECLARE @DepartementID NVARCHAR(10)
 DECLARE @DepartementName NVARCHAR(50)
 DECLARE @MONTHCHECKSTATE INT
 DECLARE @MONTHCHECKSTATES NVARCHAR(10)
 DECLARE @MONTHCHECKWORKERNAME NVARCHAR(50)
 DECLARE @MONTHCHECKDATETIME DATETIME
 DECLARE @TableFee TABLE(DEPARTMENT NVARCHAR(50),FEEITEM NVARCHAR(50),FEE decimal(18, 2),COLORCODE INT,
 MONTHCHECKSTATE NVARCHAR(10),MONTHCHECKWORKERNAME NVARCHAR(50),MONTHCHECKDATETIME DATETIME,SORT INT)
SELECT @DepartementID='02'
SELECT @DepartementName='营业股'
SELECT @MONTHCHECKSTATES=MONTHCHECKSTATES,@MONTHCHECKWORKERNAME=MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME=MONTHCHECKDATETIME FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID
INSERT INTO @TableFee SELECT @DepartementName,NULL,NULL,1,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,1
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=1
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'设计费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,2
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=2
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'工时费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,3
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=3
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'首检费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,4
 end 
    SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=4
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'基建水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,5
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=5
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'水表费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,6
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=6
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'维修费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,7
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=7
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'预存款',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,8
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=8
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'材料费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,9
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=9
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'二次加压费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,10
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID AND FeeID=10
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'补缴水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,11
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT NULL,'[合计]',@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,12
 end 
 SELECT @DepartementID='010001'
SELECT @DepartementName='技术股'
SELECT @MONTHCHECKSTATES=MONTHCHECKSTATES,@MONTHCHECKWORKERNAME=MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME=MONTHCHECKDATETIME FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID
 INSERT INTO @TableFee SELECT @DepartementName,NULL,NULL,1,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,13
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=1
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'设计费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,14
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=2
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'工时费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,15
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=3
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'首检费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,16
 end 
    SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=4
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'基建水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,17
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=5
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'水表费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,18
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=6
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'维修费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,19
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=7
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'预存款',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,20
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=8
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'材料费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,21
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=9
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'二次加压费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,22
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001' AND FeeID=10
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'补缴水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,23
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010001'
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT NULL,'[合计]',@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,24
 end 
  SELECT @DepartementID='010002'
SELECT @DepartementName='监察股'
SELECT @MONTHCHECKSTATES=MONTHCHECKSTATES,@MONTHCHECKWORKERNAME=MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME=MONTHCHECKDATETIME FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID
 INSERT INTO @TableFee SELECT @DepartementName,NULL,NULL,1,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,25
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=1
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'设计费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,26
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=2
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'工时费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,27
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=3
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'首检费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,28
 end 
    SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=4
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'基建水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,29
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=5
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'水表费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,30
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=6
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'维修费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,31
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=7
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'预存款',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,32
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=8
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'材料费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,33
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=9
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'二次加压费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,34
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002' AND FeeID=10
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'补缴水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,35
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010002'
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT NULL,'[合计]',@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,36
 end 
SELECT @DepartementID='010003'
SELECT @DepartementName='管道安装处'
SELECT @MONTHCHECKSTATES=MONTHCHECKSTATES,@MONTHCHECKWORKERNAME=MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME=MONTHCHECKDATETIME FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID
 
 INSERT INTO @TableFee SELECT @DepartementName,NULL,NULL,1,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,37
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=1
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'设计费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,38
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=2
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'工时费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,39
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=3
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'首检费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,40
 end 
    SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=4
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'基建水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,41
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=5
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'水表费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,42
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=6
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'维修费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,43
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=7
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'预存款',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,44
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=8
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'材料费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,45
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=9
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'二次加压费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,46
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003' AND FeeID=10
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'补缴水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,47
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010003'
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT NULL,'[合计]',@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,48
 end 
SELECT @DepartementID='010004'
SELECT @DepartementName='水表检定站'
SELECT @MONTHCHECKSTATES=MONTHCHECKSTATES,@MONTHCHECKWORKERNAME=MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME=MONTHCHECKDATETIME FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID

INSERT INTO @TableFee SELECT @DepartementName,NULL,NULL,1,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,49
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=1
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'设计费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,50
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=2
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'工时费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,51
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=3
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'首检费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,52
 end 
    SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=4
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'基建水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,53
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=5
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'水表费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,54
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=6
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'维修费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,55
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=7
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'预存款',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,56
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=8
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'材料费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,57
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=9
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'二次加压费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,58
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004' AND FeeID=10
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'补缴水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,59
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010004'
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT NULL,'[合计]',@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,60
 end 
SELECT @DepartementID='010005'
SELECT @DepartementName='二次加压管理办'
SELECT @MONTHCHECKSTATES=MONTHCHECKSTATES,@MONTHCHECKWORKERNAME=MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME=MONTHCHECKDATETIME FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID=@DepartementID

 INSERT INTO @TableFee SELECT @DepartementName,NULL,NULL,1,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,61
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=1
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'设计费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,62
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=2
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'工时费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,63
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=3
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'首检费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,64
 end 
    SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=4
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'基建水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,65
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=5
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'水表费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,66
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=6
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'维修费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,67
 end 
SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=7
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'预存款',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,68
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=8
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'材料费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,69
 end 
  SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=9
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'二次加压费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,70
 end 
   SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005' AND FeeID=10
 if @FEE>0
 begin
 INSERT INTO @TableFee SELECT NULL,'补缴水费',@FEE,0,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,71
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth AND DepartementID='010005'
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT NULL,'[合计]',@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,72
 end 
 SELECT @FEE=SUM(FEE) FROM View_ChargeOver WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth
 if @FEE>0
 begin
INSERT INTO @TableFee SELECT '[总计]',NULL,@FEE,2,@MONTHCHECKSTATES,@MONTHCHECKWORKERNAME,@MONTHCHECKDATETIME,73
 end 
 SELECT * FROM @TableFee", this.CB_LogID.SelectedValue, this.CB_Month.SelectedValue);


            DataTable dt = new SqlServerHelper().GetDateTableBySql(sqlstr);
            DG.DataSource = dt;
        }

        private void Btn_Settle_Click(object sender, EventArgs e)
        {
            string sqlstr = @"UPDATE View_ChargeOver SET MONTHCHECKSTATE=1,MONTHCHECKWORKERNAME=@strRealName,MONTHCHECKDATETIME=GETDATE()  WHERE CHARGEWORKERID =@LoginID AND CHARGEMONTH=@ChargeMonth";

            int count = new SqlServerHelper().UpdateByHashtable(sqlstr, new SqlParameter[] { new SqlParameter("@LoginID", this.CB_LogID.SelectedValue), new SqlParameter("@strRealName", strRealName), new SqlParameter("@ChargeMonth", CB_Month.SelectedValue) });
            if (count > 0)
            {
                MessageBox.Show("月结成功！");
                ShowData();
            }
        }

    }
}
